# -*- coding: utf-8 -*-
"""Spotify Lyric Search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NtFfH_Rd4gbdFnW59ULlFhHzNp19RpD7
"""

#Install & Import Libraries
import pandas as pd

# Load only required columns
df = pd.read_csv(
    "/content/Spotify Million Song Dataset_exported.csv",
    usecols=["artist", "song", "text"]
)

# Drop missing lyrics
df.dropna(subset=["text"], inplace=True)

# Sample for faster training
df = df.sample(50000, random_state=42)

df.reset_index(drop=True, inplace=True)
print(df.shape)

# feature Extraction
from sklearn.preprocessing import LabelEncoder

artist_encoder = LabelEncoder()
df["artist_id"] = artist_encoder.fit_transform(df["artist"])

num_artists = df["artist_id"].nunique()
print("Number of artists:", num_artists)

# Train & Testing data split
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    df["text"].astype(str).to_numpy(),
    df["artist_id"].to_numpy(),
    test_size=0.2,
    random_state=42
)

#model training using Tensorflow
import tensorflow as tf

max_tokens = 30000
sequence_length = 200

vectorizer = tf.keras.layers.TextVectorization(
    max_tokens=max_tokens,
    output_sequence_length=sequence_length
)

# Adapt only on training data
vectorizer.adapt(X_train)

model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(1,), dtype=tf.string),
    vectorizer,
    tf.keras.layers.Embedding(max_tokens, 64),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dense(num_artists, activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# Epoch wise training
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=5,
    batch_size=128
)

# use TF-IDF matrix to predict artist and song
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import tensorflow as tf

# Build TF-IDF matrix for song retrieval (run once)
tfidf = TfidfVectorizer(max_features=20000, stop_words="english")
tfidf_matrix = tfidf.fit_transform(df["text"])

def predict_artist_song():
    # Take user input
    lyrics = input("Enter lyrics snippet: ")

    # Wrap in a TensorFlow string tensor
    lyrics_tensor = tf.constant([lyrics])

    # Predict artist
    pred = model.predict(lyrics_tensor)
    artist_id = pred.argmax()
    artist = artist_encoder.inverse_transform([artist_id])[0]

    # Filter dataset to only that artist
    artist_df = df[df["artist"] == artist]

    # Predict song using TF-IDF similarity
    query_vec = tfidf.transform([lyrics])
    artist_vecs = tfidf_matrix[artist_df.index]
    sims = cosine_similarity(query_vec, artist_vecs)
    best_idx = artist_df.index[sims.argmax()]
    song = df.loc[best_idx, "song"]

    # Print results
    print("\nPredicted Artist:", artist)
    print("Predicted Song:", song)

#output
predict_artist_song()

# Use 1000 random samples from the dataset to test accuracy
test_df = df.sample(1000, random_state=42)

# Accuracy check Function
from sklearn.metrics import accuracy_score

def evaluate_model(test_df):
    y_true = test_df["artist"].tolist()
    y_pred = []

    for lyrics in test_df["text"]:
        # Transform input
        query_vec = tfidf.transform([lyrics])
        sims = cosine_similarity(query_vec, tfidf_matrix)
        best_idx = sims.argmax()
        pred_artist = df.loc[best_idx, "artist"]
        y_pred.append(pred_artist)

    acc = accuracy_score(y_true, y_pred)
    print(f"Artist Accuracy: {acc*100:.2f}%")

#model accuracy check
evaluate_model(test_df)